---
kind: pipeline
name: default
type: kubernetes

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

steps:
- name: Build
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  # Wait for the docker service to be up
  - echo "Checking for docker availability."
  - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
  - echo "echo docker now available."
  settings:
    group: build-stage
  when:
    event:
    - push
    - pull_request
    target:
      exclude:
      - production
