version: '3'

services:
  database:
    image: postgres:14
    container_name: database
    env_file:
      - .env.dev
    ports:
      - "5432:5432"

  api:
    build:
      dockerfile: Dockerfile
      context: ../data-access-api
    container_name: api
    env_file:
      - .env.dev
    depends_on:
      - database
    volumes:
      - "../data-access-api:/code"
    ports:
      - "5000:5000"

  clamav:
    image: quay.io/ukhomeofficedigital/clamav:v1.6.1
    container_name: clamav
    ports:
      - "3310:3310"

  clamav-api:
    image: quay.io/ukhomeofficedigital/docker-clamav-rest:1.0.0
    container_name: clamav-api
    environment:
      - CLAMD_HOST=clamav
      - TIMEOUT=60000
    depends_on:
      - clamav
    ports:
      - "8080:8080"

  node:
    build: .
    container_name: node
    command: sh -c 'sleep 5 && npm install nodemon && npm run dev'
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    depends_on:
      - api
      - database
      - clamav-api
    volumes:
      - ./src/app:/public-site/app
      - ./src/common:/public-site/common
      - ./src/locales:/public-site/locales
      - ./src/public:/public-site/public
      - ./src/test:/public-site/test
      - ./src/server.js:/public-site/server.js
      - ./src/start.js:/public-site/start.js
      - ./src/package.json:/public-site/package.json

