version: '3'

services:
  database:
    image: postgres:14
    container_name: database
    env_file:
      - .env.dev
    ports:
      - "5432:5432"

  api:
    build:
      dockerfile: Dockerfile
      context: ../data-access-api
    container_name: api
    env_file:
      - .env.dev
    depends_on:
      - database
    volumes:
      - "../data-access-api:/code"
    ports:
      - "5000:5000"

  mock_clamav:
    container_name: mock-clamav
    build: 
      context: ./mock_clamav
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./mock_clamav:/code

  node:
    build:
      target: development
    container_name: node
    command: sh -c 'sleep 5 && npm install nodemon && npm run dev'
    ports:
      - "3000:3000"
      - "9229:9229"
      - "9230:9230"
    env_file:
      - .env.dev
    depends_on:
      - api
      - database
    volumes:
      - ./src/:/public-site/
