version: '3'

services:

  database:
    image: postgres:10.4
    container_name: database
    env_file:
      - .env.dev
    ports:
      - "5432:5432"

  api:
    image: api
    container_name: api
    env_file:
      - .env.dev
    depends_on:
      - database
    ports:
      - "5000:5000"

  clamav:
    image: quay.io/ukhomeofficedigital/clamav:v1.6.1
    container_name: clamav
    ports:
      - "3310:3310"

  clamav-api:
    image: quay.io/ukhomeofficedigital/docker-clamav-rest:1.0.0
    container_name: clamav-api
    environment:
      - CLAMD_HOST=clamav
      - TIMEOUT=60000
    depends_on:
      - clamav
    ports:
      - "8080:8080"

  node:
    build: .
    container_name: node
    command: sh -c 'sleep 5 && npm install nodemon && npm run dev'
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    depends_on:
      - api
      - database
      - clamav-api
    volumes:
      - ./src/app:/public-site/app
      - ./src/common:/public-site/common
      - ./src/locales:/public-site/locales
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3,sqs
      - DEBUG=1
      - LS_LOG=trace
    ports: 
      - '4566-4583:4566-4583'
    volumes: 
      - "${TEMPDIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack/start.sh:/etc/localstack/init/ready.d/start.sh"