---
apiVersion: v1
kind: Secret
metadata:
  name: artifactory-secret
  namespace: {{ .KUBE_NAMESPACE }}
data:
  .dockerconfigjson: {{ .KUBE_ARTIFACTORY_APP_SECRET }}
type: kubernetes.io/dockerconfigjson
