---
apiVersion: v1
kind: Service
metadata:
  name: public-site-svc
  labels:
    name: public-site-svc
spec:
  selector:
    app.kubernetes.io/name: public-site-svc
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 10443
