apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: public-site-cert
  labels:
    # @Note: specify label cert-manager.io/solver to specify that the route53 dns01 solver should be used
    cert-manager.io/solver: route53
spec:
  secretName: public-site-tls-cmio
  issuerRef:
    # use letsencrypt-staging while developing and testing your certificates
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - public-site.dev-external.egar-notprod.homeoffice.gov.uk
    - public-site.dev-internal.egar-notprod.homeoffice.gov.uk
