---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-site-ingress
  labels:
    cert-manager.io/solver: route53
  annotations:
    kubernetes.io/ingress.class: "nginx-internal"
    cert-manager.io/enabled: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/proxy-body-size: "20m"
    ingress.kubernetes.io/ssl-ciphers: '!aNULL:!EXPORT56:TLSv1.3:TLSv1.2:+HIGH'
    ingress.kubernetes.io/ssl-protocols: TLSv1.2 TLSv1.3
spec:
  tls:
  - hosts:
    - {{ .PUBLIC_SITE_INTERNAL_URL }}
    secretName: public-site-internal-tls
  rules:
  - host: {{ .PUBLIC_SITE_INTERNAL_URL }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service: 
            name: public-site-svc
            port:
              number: 10443

              