---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-site
  namespace: {{ .KUBE_NAMESPACE }}
spec:
  selector:
    matchLabels:
      name: {{ .APP_NAME }}-svc
      service: {{ .APP_NAME }}-svc
  replicas: {{.NUM_REPLICAS}}
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        name: public-site-svc
        service: public-site-svc
    spec:
      containers:
        - name: public-site-proxy
          image: quay.io/ukhomeofficedigital/acp-nginx-proxy-rocky:0.0.3
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            privileged: false
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - name: public-prxy-prt
              containerPort: 10443
          env:
            - name: PROXY_SERVICE_HOST
              value: "127.0.0.1"
            - name: PROXY_SERVICE_PORT
              value: "3000"
            - name: NAXSI_USE_DEFAULT_RULES
              value: "FALSE"
            - name: ENABLE_UUID_PARAM
              value: "FALSE"
            - name: ADD_NGINX_SERVER_CFG
              value: "add_header Strict-Transport-Security \"max-age=31536000; includeSubDomains\" always;"
            - name: CLIENT_MAX_BODY_SIZE
              value: '20'
            - name: STATSD_METRICS
              value: 'FALSE'
        - name: public-site
          image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/egar/public-site-ui:{{ .TAGGED_VERSION }}
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            privileged: false
          resources:
            limits:
              memory: "4096Mi"
              cpu: "4000m"
            requests:
              memory: "2048Mi"
              cpu: "2000m"
          env:
            - name: LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: LOG_LEVEL
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: NODE_TLS_REJECT_UNAUTHORIZED
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: BASE_URL
            - name: API_BASE
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: API_BASE
            - name: API_VERSION
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: API_VERSION
            - name: CLAMAV_BASE
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: CLAMAV_BASE
            - name: CLAMAV_PORT
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: CLAMAV_PORT
            - name: NOTIFY_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: NOTIFY_TOKEN_SECRET
            - name: NOTIFY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: NOTIFY_API_KEY
            - name: NOTIFY_TOKEN_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: NOTIFY_TOKEN_TEMPLATE_ID
            - name: NOTIFY_INVITE_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: NOTIFY_INVITE_TEMPLATE_ID
            - name: NOTIFY_GAR_CANCEL_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: NOTIFY_GAR_CANCEL_TEMPLATE_ID
            - name: NOTIFY_GAR_SUBMISSION_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: NOTIFY_GAR_SUBMISSION_TEMPLATE_ID
            - name: NOTIFY_ACCOUNT_DELETE_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: NOTIFY_ACCOUNT_DELETE_TEMPLATE_ID
            - name: NOTIFY_MFA_TOKEN_LENGTH
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: NOTIFY_MFA_TOKEN_LENGTH
            - name: NOTIFY_MFA_TOKEN_TTL
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: NOTIFY_MFA_TOKEN_TTL
            - name: NOTIFY_MFA_TOKEN_MAX_ATTEMPTS
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: NOTIFY_MFA_TOKEN_MAX_ATTEMPTS
            - name: NOTIFY_MFA_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: NOTIFY_MFA_TEMPLATE_ID
            - name: NOTIFY_ORGANISATION_DELETE_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: NOTIFY_ORGANISATION_DELETE_TEMPLATE_ID
            - name: PUBLIC_SITE_DBHOST
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: PUBLIC_SITE_DBHOST
            - name: PUBLIC_SITE_DBPORT
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: PUBLIC_SITE_DBPORT
            - name: PUBLIC_SITE_DBNAME
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: PUBLIC_SITE_DBNAME
            - name: CARRIER_SUPPORT_HUB_UK_NUMBER
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: CARRIER_SUPPORT_HUB_UK_NUMBER
            - name: CARRIER_SUPPORT_HUB_INTERNATIONAL_NUMBER
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: CARRIER_SUPPORT_HUB_INTERNATIONAL_NUMBER
            - name: PUBLIC_SITE_DBUSER
              valueFrom:
                secretKeyRef:
                  name: appdbcreds
                  key: FRONTENDDBUSER
            - name: PUBLIC_SITE_DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: appdbcreds
                  key: FRONTENDDBPASSWORD
            - name: SESSION_PARSER_SECRET
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: SESSION_PARSER_SECRET
            - name: SESSION_ENCODE_SECRET
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: SESSION_ENCODE_SECRET
            - name: SESSION_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: SESSION_TIMEOUT
            - name: COOKIE_SECURE_FLAG
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: COOKIE_SECURE_FLAG
            - name: GA_ID
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: GA_ID
            - name: G4_ID
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: G4_ID
            - name: NOTIFY_NOT_REGISTERED_TEMPLATE_ID
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: NOTIFY_NOT_REGISTERED_TEMPLATE_ID
            - name: WHITELIST_REQUIRED
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: WHITELIST_REQUIRED
            - name: ENABLE_UNAVAILABLE_PAGE
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: ENABLE_UNAVAILABLE_PAGE
            - name: USER_FIRST_NAME_CHARACTER_COUNT
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: USER_FIRST_NAME_CHARACTER_COUNT
            - name: USER_SURNAME_CHARACTER_COUNT
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: USER_SURNAME_CHARACTER_COUNT
            - name: IS_PLANNED_MAINTENANCE
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: IS_PLANNED_MAINTENANCE
            - name: MAINTENANCE_START_DATETIME
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: MAINTENANCE_START_DATETIME
            - name: MAINTENANCE_END_DATETIME
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: MAINTENANCE_END_DATETIME
            - name: MAX_NUM_FILES
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: MAX_NUM_FILES
            - name: HOMEPAGE_MESSAGE
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: HOMEPAGE_MESSAGE        
          ports:
            - name: public-site-prt
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 10443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 300
