apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
  namespace: {{ .KUBE_NAMESPACE }}
type: Opaque
stringData:
  username: admin # required field for kubernetes.io/basic-auth
  password: t0p-Secret # required field for kubernetes.io/basic-auth