envData:
  API_VERSION: "v0.2.0"
  CLAMAV_BASE: "http://localhost"
  CLAMAV_PORT: "8080"
  NOTIFY_MFA_TOKEN_LENGTH: "8"
  NOTIFY_MFA_TOKEN_TTL: "5"
  NOTIFY_MFA_TOKEN_MAX_ATTEMPTS: "5"
  PUBLIC_SITE_DBPORT: "5432"
  SESSION_TIMEOUT: "3600000"
  COOKIE_SECURE_FLAG: "true"
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
