// Unavailable page setting
const ENABLE_UNAVAILABLE_PAGE = process.env.ENABLE_UNAVAILABLE_PAGE || 'false';

const IS_PLANNED_MAINTENANCE = process.env.IS_PLANNED_MAINTENANCE || 'false';
const MAINTENANCE_START_DATETIME = process.env.MAINTENANCE_START_DATETIME || 'unknown';
const MAINTENANCE_END_DATETIME = process.env.MAINTENANCE_END_DATETIME || 'unknown';

export default {
    ENABLE_UNAVAILABLE_PAGE,
    IS_PLANNED_MAINTENANCE,
    MAINTENANCE_START_DATETIME,
    MAINTENANCE_END_DATETIME,
};