// Gov notify settings
export const NOTIFY_API_KEY = process.env.NOTIFY_API_KEY;

export const NOTIFY_TOKEN_TEMPLATE_ID = process.env.NOTIFY_TOKEN_TEMPLATE_ID;
export const NOTIFY_RECEIPT_TEMPLATE_ID = '3bc1e2ab-59d4-438e-b896-499f9c811fd6';
export const NOTIFY_INTERNAL_TEMPLATE_ID = '2bc9954d-e07f-44e7-a691-e53d8d1400fd';
export const NOTIFY_INVITE_TEMPLATE_ID = process.env.NOTIFY_INVITE_TEMPLATE_ID;
export const NOTIFY_TOKEN_SECRET = process.env.NOTIFY_TOKEN_SECRET;
export const NOTIFY_GAR_CANCEL_TEMPLATE_ID = process.env.NOTIFY_GAR_CANCEL_TEMPLATE_ID;
export const NOTIFY_GAR_SUBMISSION_TEMPLATE_ID = process.env.NOTIFY_GAR_SUBMISSION_TEMPLATE_ID;
export const NOTIFY_MFA_TEMPLATE_ID = process.env.NOTIFY_MFA_TEMPLATE_ID;
export const NOTIFY_ACCOUNT_DELETE_TEMPLATE_ID = process.env.NOTIFY_ACCOUNT_DELETE_TEMPLATE_ID;
export const NOTIFY_ORGANISATION_DELETE_TEMPLATE_ID = process.env.NOTIFY_ORGANISATION_DELETE_TEMPLATE_ID;
export const NOTIFY_NOT_REGISTERED_TEMPLATE_ID = process.env.NOTIFY_NOT_REGISTERED_TEMPLATE_ID;
export const NOTIFY_ONE_LOGIN_INVITE_TEMPLATE_ID = process.env.NOTIFY_ONE_LOGIN_INVITE_TEMPLATE_ID;

// Server settings
export const SESSION_ENCODE_SECRET = process.env.SESSION_ENCODE_SECRET || 'thisShouldBeLongAndSecret';

export const SESSION_PARSER_SECRET = process.env.SESSION_PARSER_SECRET || '3169n$*INDUKFIN*s47y4917$p';
//todo sort this shit out. Copilot. How very dare you?
const config = {
    NOTIFY_API_KEY: process.env.NOTIFY_API_KEY,
    NOTIFY_TOKEN_TEMPLATE_ID: process.env.NOTIFY_TOKEN_TEMPLATE_ID,
    NOTIFY_RECEIPT_TEMPLATE_ID: '3bc1e2ab-59d4-438e-b896-499f9c811fd6',
    NOTIFY_INTERNAL_TEMPLATE_ID: '2bc9954d-e07f-44e7-a691-e53d8d1400fd',
    NOTIFY_INVITE_TEMPLATE_ID: process.env.NOTIFY_INVITE_TEMPLATE_ID,
    NOTIFY_TOKEN_SECRET: process.env.NOTIFY_TOKEN_SECRET,
    NOTIFY_GAR_CANCEL_TEMPLATE_ID: process.env.NOTIFY_GAR_CANCEL_TEMPLATE_ID,
    NOTIFY_GAR_SUBMISSION_TEMPLATE_ID: process.env.NOTIFY_GAR_SUBMISSION_TEMPLATE_ID,
    NOTIFY_MFA_TEMPLATE_ID: process.env.NOTIFY_MFA_TEMPLATE_ID,
    NOTIFY_ACCOUNT_DELETE_TEMPLATE_ID: process.env.NOTIFY_ACCOUNT_DELETE_TEMPLATE_ID,
    NOTIFY_ORGANISATION_DELETE_TEMPLATE_ID: process.env.NOTIFY_ORGANISATION_DELETE_TEMPLATE_ID,
    NOTIFY_NOT_REGISTERED_TEMPLATE_ID: process.env.NOTIFY_NOT_REGISTERED_TEMPLATE_ID,
    NOTIFY_ONE_LOGIN_INVITE_TEMPLATE_ID: process.env.NOTIFY_ONE_LOGIN_INVITE_TEMPLATE_ID,
    SESSION_ENCODE_SECRET: process.env.SESSION_ENCODE_SECRET || 'thisShouldBeLongAndSecret',
    SESSION_PARSER_SECRET: process.env.SESSION_PARSER_SECRET || '3169n$*INDUKFIN*s47y4917$p',
    API_BASE: process.env.API_BASE || 'http://localhost:5000',
    API_VERSION: process.env.API_VERSION || 'v0.2.0',
    CORRELATION_HEADER: process.env.CORRELATION_HEADER_NAME || 'x-request-id',
    CONNECTOR_URL: process.env.CONNECTOR_URL,
    CONTACT_EMAIL: process.env.CONTACT_URL || 'supportegar@homeoffice.gov.uk',
    WHITELIST_REQUIRED: process.env.WHITELIST_REQUIRED || 'true',
    NODE_ENV: process.env.NODE_ENV || 'DEV',
    FLAGPOLE_MAINTENANCE: process.env.FLAGPOLE_MAINTENANCE,
    LOG_LEVEL: process.env.LOG_LEVEL || 'info',
    BASE_URL: process.env.BASE_URL || 'http://localhost:3000',
    SESSION_TIMEOUT: process.env.SESSION_TIMEOUT || '3600000',
    COOKIE_SECURE_FLAG: process.env.COOKIE_SECURE_FLAG || 'false',
    MAX_STRING_LENGTH: 35,
    MAX_POSTCODE_LENGTH: 13,
    MAX_REGISTRATION_LENGTH: 15,
    MAX_EMAIL_LENGTH: 150,
    MAX_ADDRESS_LINE_LENGTH: 250,
    MAX_TEXT_BOX_LENGTH: 250,
    USER_FIRST_NAME_CHARACTER_COUNT: process.env.USER_FIRST_NAME_CHARACTER_COUNT || 25,
    USER_GIVEN_NAME_CHARACTER_COUNT: 50,
    USER_SURNAME_CHARACTER_COUNT: process.env.USER_SURNAME_CHARACTER_COUNT || 25,
    CLAMAV_BASE: process.env.CLAMAV_BASE,
    CLAMAV_PORT: process.env.CLAMAV_PORT,
    PUBLIC_SITE_DBHOST: process.env.PUBLIC_SITE_DBHOST,
    PUBLIC_SITE_DBPORT: process.env.PUBLIC_SITE_DBPORT,
    PUBLIC_SITE_DBNAME: process.env.PUBLIC_SITE_DBNAME,
    PUBLIC_SITE_DBUSER: process.env.PUBLIC_SITE_DBUSER,
    PUBLIC_SITE_DBPASSWORD: process.env.PUBLIC_SITE_DBPASSWORD,
    DATABASE_DIALECT: 'postgres',
    PUBLIC_SITE_DB_CONNSTR: `postgres://${process.env.PUBLIC_SITE_DBUSER}:${process.env.PUBLIC_SITE_DBPASSWORD}@${process.env.PUBLIC_SITE_DBHOST}:${process.env.PUBLIC_SITE_DBPORT}/${process.env.PUBLIC_SITE_DBNAME}`,
    NODE_TLS_REJECT_UNAUTHORIZED: 1,
    MFA_TOKEN_LENGTH: parseInt(process.env.NOTIFY_MFA_TOKEN_LENGTH, 10) || 8,
    MFA_TOKEN_EXPIRY: parseInt(process.env.NOTIFY_MFA_TOKEN_TTL, 10) || 5,
    MFA_TOKEN_MAX_ATTEMPTS: parseInt(process.env.NOTIFY_MFA_TOKEN_MAX_ATTEMPTS, 10) || 5,
    MAX_NUM_FILES: parseInt(process.env.MAX_NUM_FILES, 10) || 8,
    HOMEPAGE_MESSAGE: process.env.HOMEPAGE_MESSAGE,
    MAX_ALLOWED_CANCELLATION_TIME_TO_CBP: 2 * 7 * 24 * 60 * 60 * 1000,
    CARRIER_SUPPORT_HUB_UK_NUMBER: process.env.CARRIER_SUPPORT_HUB_UK_NUMBER,
    CARRIER_SUPPORT_HUB_INTERNATIONAL_NUMBER: process.env.CARRIER_SUPPORT_HUB_INTERNATIONAL_NUMBER,
    ONE_LOGIN_PRIVATE_KEY: process.env.ONE_LOGIN_PRIVATE_KEY,
    ONE_LOGIN_CLIENT_ID: process.env.ONE_LOGIN_CLIENT_ID,
    ONE_LOGIN_INTEGRATION_URL: process.env.ONE_LOGIN_INTEGRATION_URL,
    ONE_LOGIN_REDIRECT_URI: process.env.ONE_LOGIN_REDIRECT_URI,
    ONE_LOGIN_LOGOUT_URL: process.env.ONE_LOGIN_LOGOUT_URL,
    ONE_LOGIN_PUBLIC_KEY: process.env.ONE_LOGIN_PUBLIC_KEY,
    ONE_LOGIN_POST_MIGRATION: process.env.ONE_LOGIN_POST_MIGRATION === 'true',
    ONE_LOGIN_SHOW_ONE_LOGIN: process.env.ONE_LOGIN_SHOW_ONE_LOGIN === 'true',
    ONE_LOGIN_ACCOUNT_URL: process.env.ONE_LOGIN_ACCOUNT_URL,
    IS_HTTPS_SERVER: process.env.BASE_URL ? !process.env.BASE_URL.startsWith("http://localhost") : true,
    SAME_SITE_VALUE: process.env.BASE_URL ? (!process.env.BASE_URL.startsWith("http://localhost") ? 'None' : 'Lax') : 'None',
    NOTIFY_ONELOGIN_NEW_USER_REGISTERED_EMAIL_TEMPLATE_ID: process.env.NOTIFY_ONELOGIN_NEW_USER_REGISTERED_EMAIL_TEMPLATE_ID,
    NOTIFY_ADMIN_ABOUT_USER_EMAIL_CHANGE_TEMPLATE_ID: process.env.NOTIFY_ADMIN_ABOUT_USER_EMAIL_CHANGE_TEMPLATE_ID,
    NOTIFY_ONELOGIN_ACCOUNT_DELETE_TEMPLATE_ID: process.env.NOTIFY_ONELOGIN_ACCOUNT_DELETE_TEMPLATE_ID,
};

export default config;
// API settings
export const API_BASE = process.env.API_BASE || 'http://localhost:5000';

export const API_VERSION = process.env.API_VERSION || 'v0.2.0';

// Misc settings
export const CORRELATION_HEADER = process.env.CORRELATION_HEADER_NAME || 'x-request-id';

export const CONNECTOR_URL = process.env.CONNECTOR_URL;
export const CONTACT_EMAIL = process.env.CONTACT_URL || 'supportegar@homeoffice.gov.uk';
export const WHITELIST_REQUIRED = process.env.WHITELIST_REQUIRED || 'true';

// Application settings
export const NODE_ENV = process.env.NODE_ENV || 'DEV';

export const FLAGPOLE_MAINTENANCE = process.env.FLAGPOLE_MAINTENANCE;
export const LOG_LEVEL = process.env.LOG_LEVEL || 'info';
export const BASE_URL = process.env.BASE_URL || 'http://localhost:3000';
export const SESSION_TIMEOUT = process.env.SESSION_TIMEOUT || '3600000';
export const COOKIE_SECURE_FLAG = process.env.COOKIE_SECURE_FLAG || 'false';

// Application form validation settings
export const MAX_STRING_LENGTH = 35;

export const MAX_POSTCODE_LENGTH = 13;
export const MAX_REGISTRATION_LENGTH = 15;
export const MAX_EMAIL_LENGTH = 150;
export const MAX_ADDRESS_LINE_LENGTH = 250;
export const MAX_TEXT_BOX_LENGTH = 250;
export const USER_FIRST_NAME_CHARACTER_COUNT = process.env.USER_FIRST_NAME_CHARACTER_COUNT || 25;
export const USER_GIVEN_NAME_CHARACTER_COUNT = 50;
export const USER_SURNAME_CHARACTER_COUNT = process.env.USER_SURNAME_CHARACTER_COUNT || 25;

// ClamAv settings
export const CLAMAV_BASE = process.env.CLAMAV_BASE;

export const CLAMAV_PORT = process.env.CLAMAV_PORT;

// DB settings
export const PUBLIC_SITE_DBHOST = process.env.PUBLIC_SITE_DBHOST;

export const PUBLIC_SITE_DBPORT = process.env.PUBLIC_SITE_DBPORT;
export const PUBLIC_SITE_DBNAME = process.env.PUBLIC_SITE_DBNAME;
export const PUBLIC_SITE_DBUSER = process.env.PUBLIC_SITE_DBUSER;
export const PUBLIC_SITE_DBPASSWORD = process.env.PUBLIC_SITE_DBPASSWORD;
export const DATABASE_DIALECT = 'postgres';
export const PUBLIC_SITE_DB_CONNSTR = `postgres://${process.env.PUBLIC_SITE_DBUSER}:${process.env.PUBLIC_SITE_DBPASSWORD}@${process.env.PUBLIC_SITE_DBHOST}:${process.env.PUBLIC_SITE_DBPORT}/${process.env.PUBLIC_SITE_DBNAME}`;

// TLS settings
export const NODE_TLS_REJECT_UNAUTHORIZED = 1;

// Token settings
export const MFA_TOKEN_LENGTH = parseInt(process.env.NOTIFY_MFA_TOKEN_LENGTH, 10) || 8;

export const MFA_TOKEN_EXPIRY = parseInt(process.env.NOTIFY_MFA_TOKEN_TTL, 10) || 5;
export const MFA_TOKEN_MAX_ATTEMPTS = parseInt(process.env.NOTIFY_MFA_TOKEN_MAX_ATTEMPTS, 10) || 5;

//MAX NUMBER OF FILES
export const MAX_NUM_FILES = parseInt(process.env.MAX_NUM_FILES, 10) || 8;

//Homepage banner message
export const HOMEPAGE_MESSAGE = process.env.HOMEPAGE_MESSAGE;

// Max allowed cancellation to CBP - 2 weeks
export const MAX_ALLOWED_CANCELLATION_TIME_TO_CBP = 2 * 7 * 24 * 60 * 60 * 1000;

export const CARRIER_SUPPORT_HUB_UK_NUMBER = process.env.CARRIER_SUPPORT_HUB_UK_NUMBER;
export const CARRIER_SUPPORT_HUB_INTERNATIONAL_NUMBER = process.env.CARRIER_SUPPORT_HUB_INTERNATIONAL_NUMBER;

//One Login
export const ONE_LOGIN_PRIVATE_KEY = process.env.ONE_LOGIN_PRIVATE_KEY;

export const ONE_LOGIN_CLIENT_ID = process.env.ONE_LOGIN_CLIENT_ID;
export const ONE_LOGIN_INTEGRATION_URL = process.env.ONE_LOGIN_INTEGRATION_URL;
export const ONE_LOGIN_REDIRECT_URI = process.env.ONE_LOGIN_REDIRECT_URI;
export const ONE_LOGIN_LOGOUT_URL = process.env.ONE_LOGIN_LOGOUT_URL;
export const ONE_LOGIN_PUBLIC_KEY = process.env.ONE_LOGIN_PUBLIC_KEY;
export const ONE_LOGIN_POST_MIGRATION = process.env.ONE_LOGIN_POST_MIGRATION === 'true';
export const ONE_LOGIN_SHOW_ONE_LOGIN = process.env.ONE_LOGIN_SHOW_ONE_LOGIN === 'true';
export const ONE_LOGIN_ACCOUNT_URL = process.env.ONE_LOGIN_ACCOUNT_URL;
export const IS_HTTPS_SERVER = process.env.BASE_URL ? !process.env.BASE_URL.startsWith("http://localhost") : true;
export const SAME_SITE_VALUE = IS_HTTPS_SERVER ? 'None' : 'Lax';
export const NOTIFY_ONELOGIN_NEW_USER_REGISTERED_EMAIL_TEMPLATE_ID = process.env.NOTIFY_ONELOGIN_NEW_USER_REGISTERED_EMAIL_TEMPLATE_ID;
export const NOTIFY_ADMIN_ABOUT_USER_EMAIL_CHANGE_TEMPLATE_ID = process.env.NOTIFY_ADMIN_ABOUT_USER_EMAIL_CHANGE_TEMPLATE_ID;
export const NOTIFY_ONELOGIN_ACCOUNT_DELETE_TEMPLATE_ID = process.env.NOTIFY_ONELOGIN_ACCOUNT_DELETE_TEMPLATE_ID;
