{{- if .Values.svc_ingress_enabled | default false -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.global.publicsiteui.appName }}-svc-ingress
  labels:
    cert-manager.io/solver: http01
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/proxy-body-size: "20m"
    cert-manager.io/enabled: "true"
spec:
  rules:
  - host: {{ .Values.global.publicsiteui.envData.BASE_URL_SERVICE }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.global.publicsiteui.appName }}-svc
          servicePort: public-prxy-prt
        path: /
  tls:
  - hosts:
    - {{ .Values.global.publicsiteui.envData.BASE_URL_SERVICE }}
    secretName: {{ .Values.global.publicsiteui.appName }}-svc-tls-cmio
{{- end }}