export TAGGED_VERSION=${DRONE_COMMIT}
export KUBE_SERVER=${DEV_KUBE_SERVER}
export KUBE_TOKEN=${DEV_KUBE_TOKEN}
export PUBLIC_SITE_EXTERNAL_URL=${DEV_URL_SERVICE}
export PUBLIC_SITE_INTERNAL_URL=${DEV_BASE_URL}
# export KUBE_ARTIFACTORY_APP_SECRET=${DEV_KUBE_ARTIFACTORY_APP_SECRET}
source ./ops/common_lib
source ./ops/prod_values