export TAGGED_VERSION=${DRONE_COMMIT}
# export KUBE_ARTIFACTORY_APP_SECRET=$${SIT_KUBE_ARTIFACTORY_APP_SECRET}
export KUBE_SERVER=${SIT_KUBE_SERVER}
export KUBE_TOKEN=${SIT_KUBE_TOKEN}
export PUBLIC_SITE_EXTERNAL_URL=${SIT_BASE_URL_SERVICE}
export PUBLIC_SITE_INTERNAL_URL=${SIT_BASE_URL}
source ./ops/common_lib
source ./ops/notprod_values