export TAGGED_VERSION=${DRONE_COMMIT}
export DOCKER_REGISTRY_URL=${DOCKER_REGISTRY_URL}
# export KUBE_ARTIFACTORY_APP_SECRET=$${STAGING_KUBE_ARTIFACTORY_APP_SECRET}
export KUBE_SERVER=${STAGING_KUBE_SERVER}
export KUBE_TOKEN=${STAGING_KUBE_TOKEN}
export PUBLIC_SITE_EXTERNAL_URL=${STAGING_BASE_URL_SERVICE}
export PUBLIC_SITE_INTERNAL_URL=${STAGING_BASE_URL}
source ./ops/common_lib
source ./ops/notprod_values