name: RDS Connectivity Test

on:
  workflow_dispatch:

jobs:
  test-db:
    runs-on: ubuntu-latest

    steps:
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y dnsutils netcat-openbsd

      - name: Test DNS resolution
        run: |
          nslookup egarnotprod.cptlzykvnlia.eu-west-2.rds.amazonaws.com

      - name: Test PostgreSQL port
        run: |
          nc -zv egarnotprod.cptlzykvnlia.eu-west-2.rds.amazonaws.com 5432
