name: GitHub Runner Test

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Print system info
        run: |
          echo "Runner working"
          uname -a
          python3 --version
